/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snpBasicStatc;

import java.awt.GridLayout;
import java.util.ArrayList;

/**
 *
 * @author Loena
 */
public class TodosIndividuosGUI extends javax.swing.JPanel {
ProcesarEstructura procesar;
ArrayList<SNP> snp;
        

    public TodosIndividuosGUI() {
        super(new GridLayout(1,0));
        procesar = new ProcesarEstructura();
        snp = new ArrayList<SNP>();
        procesar.Procesar_Archivo();
        snp= procesar.arregloSNP;
         
        initComponents();
    }
    
    public void FrecuenciasAlelicasCasoControl()
    {
        String[] columnNames = {"Alelo",
                                "Conteo",
                                "Proporcion",
                                "Controles - 0 ",
                                "Proporcion","Casos - 1", "Proporcion"};
        Object[][] data= new Object[snp.size()*2][columnNames.length];
        
       /* for(int i=0;i<snp.size();i++)
        {
          for(int j=0; j<columnNames.length;j++)
          { 
              
              data[i][]={}
              
              
            System.out.println( snp.get(numhilo).homocigotoMayorFr.getTipo().substring(0,1)+"         "+snp.get(numhilo).ConteoAlelosMayorFr()+"          "+snp.get(numhilo).frecuenciasAlelicasTodosAleloMayorFr());
            System.out.println( snp.get(numhilo).homocigotoMenorFr.getTipo().substring(0,1)+ "         "+snp.get(numhilo).ConteoAlelosMenorFr() +"          "+snp.get(numhilo).frecuenciasAlelicasTodosAleloMenorFr());
          }
        }
        
    }*/}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
